name: Upload files to Tencent Cloud COS (incremental)

description: Upload local files in a directory to Tencent Cloud COS with a prefix incrementally, with filename filter.

branding:
  icon: upload-cloud
  color: orange

inputs:
  secret-id:
    description: The secretId used to authenticate with Tencent Cloud.
    default: ''
  secret-key:
    description: The secretKey used to authenticate with Tencent Cloud.
    default: ''
  bucket:
    description: The Aliyun OSS bucket name to upload to.
    required: true
  region:
    description: The Tencent Cloud COS region used to upload.
    required: true
  accelerate:
    description: Whether or not to use accelerate domain.
    default: 'false'
  local-path:
    description: The local path of directory to upload. Must point to a directory.
    required: true
  remote-path:
    description: The remote path (prefix) to upload to.
    required: true
  include-regex:
    description: The regex of filenames included. All files by default.
    default: ''
  exclude-regex:
    description: The regex of filenames excluded. A file is ignored when matching it even if it matches `include-regex`.
    default: '^$'
  delay-html-file-upload:
    description: Whether or not to delay upload of HTML file after other files.
    default: 'false'
  no-delete-remote-files:
    description: Whether or not to keep missing remote files compared to local.
    default: 'false'
    required: false
  retry:
    description: Retry times for each COS operation. Default is 5.
    default: '5'
    required: false
  incremental:
    description: Upload files whose content changed only.
    default: 'true'
    required: false

runs:
  using: node16
  main: bootstrap.js
